services:
  - type: web
    name: huttohut-chat
    env: node
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: PORT
        value: 10000
    plan: free 