services:
  - type: web
    name: huttohut-chat
    env: node
    buildCommand: npm install -g pnpm && cd client && npm install && npm run build && cd ../server && pnpm install && pnpm run build
    startCommand: cd server && node dist/index.js
    envVars:
      - key: PORT
        value: 10000
    plan: free 